import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Element from '.././assets/global/element.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <div className="w-7/10 absolute h-hd">
          <Image
            src={Element}

            alt="Element"
            className="object-cover w-[64vw] h-[100vh]"
          />
        </div>
        <div className="w-3/10 relative z-50 ">
          {children}
        </div>
      </body>
    </html>
  );
}